### ISSUE TITLE
Erro ao tentar executar a automação exemplo

### ISSUE THREAD

**Issue by victoroesilva** [FrameworkOpenBDT/archetype-web#6]
@org.junit.runner.RunWith(value=class net.serenitybdd.cucumber.CucumberWithSerenity)
@cucumber.api.CucumberOptions(features=[src/test/resources/bdd/features], junit=[], dryRun=false, plugin=[], glue=[br.com.edglobo.globocore.steps.definition], snippets=UNDERSCORE, name=[], format=[], monochrome=true, strict=false, tags=[])
@org.springframework.stereotype.Component(value=)
@org.springframework.beans.factory.annotation.Qualifier(value=webSetup)
15:40:22  INFO [RunListenerJunit    ] ------------------------------------------------------------------------------------------------------------------------------------------------
     OOOOOOOOO                                                               BBBBBBBBBBBBBBBBB   DDDDDDDDDDDDD        TTTTTTTTTTTTTTTTTTTTTTT
   OO:::::::::OO                                                             B::::::::::::::::B  D::::::::::::DDD     T:::::::::::::::::::::T
 OO:::::::::::::OO                                                           B::::::BBBBBB:::::B D:::::::::::::::DD   T:::::::::::::::::::::T
O:::::::OOO:::::::O                                                          BB:::::B     B:::::BDDD:::::DDDDD:::::D  T:::::TT:::::::TT:::::T
O::::::O   O::::::Oppppp   ppppppppp       eeeeeeeeeeee    nnnn  nnnnnnnn      B::::B     B:::::B  D:::::D    D:::::D TTTTTT  T:::::T  TTTTTT
O:::::O     O:::::Op::::ppp:::::::::p    ee::::::::::::ee  n:::nn::::::::nn    B::::B     B:::::B  D:::::D     D:::::D        T:::::T        
O:::::O     O:::::Op:::::::::::::::::p  e::::::eeeee:::::een::::::::::::::nn   B::::BBBBBB:::::B   D:::::D     D:::::D        T:::::T        
O:::::O     O:::::Opp::::::ppppp::::::pe::::::e     e:::::enn:::::::::::::::n  B:::::::::::::BB    D:::::D     D:::::D        T:::::T        
O:::::O     O:::::O p:::::p     p:::::pe:::::::eeeee::::::e  n:::::nnnn:::::n  B::::BBBBBB:::::B   D:::::D     D:::::D        T:::::T        
O:::::O     O:::::O p:::::p     p:::::pe:::::::::::::::::e   n::::n    n::::n  B::::B     B:::::B  D:::::D     D:::::D        T:::::T        
O:::::O     O:::::O p:::::p     p:::::pe::::::eeeeeeeeeee    n::::n    n::::n  B::::B     B:::::B  D:::::D     D:::::D        T:::::T        
O::::::O   O::::::O p:::::p    p::::::pe:::::::e             n::::n    n::::n  B::::B     B:::::B  D:::::D    D:::::D         T:::::T        
O:::::::OOO:::::::O p:::::ppppp:::::::pe::::::::e            n::::n    n::::nBB:::::BBBBBB::::::BDDD:::::DDDDD:::::D        TT:::::::TT      
 OO:::::::::::::OO  p::::::::::::::::p  e::::::::eeeeeeee    n::::n    n::::nB:::::::::::::::::B D:::::::::::::::DD         T:::::::::T      
   OO:::::::::OO    p::::::::::::::pp    ee:::::::::::::e    n::::n    n::::nB::::::::::::::::B  D::::::::::::DDD           T:::::::::T      
     OOOOOOOOO      p::::::pppppppp        eeeeeeeeeeeeee    nnnnnn    nnnnnnBBBBBBBBBBBBBBBBB   DDDDDDDDDDDDD              TTTTTTTTTTT      
                    p:::::p                                                                                                                  
                    p:::::p                                                                                                                  
                   p:::::::p                                                                                                                 
                   p:::::::p                                                                                                                 
                   p:::::::p                                                                                                                 
                   ppppppppp																												     
------------------------------------------------------------------------------------------------------------------------------------------------

15:40:22  INFO [RunListenerJunit    ] test run started: null
15:40:22  INFO [RunListenerJunit    ] test started: initializationError(br.com.edglobo.globocore.setup.WebSetupImpl)
15:40:22  INFO [RunListenerJunit    ] test Failure: initializationError(br.com.edglobo.globocore.setup.WebSetupImpl): Illegal char <|> at index 33: bdd/report/output/folder[relative|absolute]
15:40:22  INFO [RunListenerJunit    ] test finished: initializationError(br.com.edglobo.globocore.setup.WebSetupImpl)
15:40:22  INFO [RunListenerJunit    ] test run finished: org.junit.runner.Result@4bee18dc
Exception: java.nio.file.InvalidPathException: Illegal char <|> at index 33: bdd/report/output/folder[relative|absolute]
Message: Illegal char <|> at index 33: bdd/report/output/folder[relative|absolute]
Trace: java.nio.file.InvalidPathException: Illegal char <|> at index 33: bdd/report/output/folder[relative|absolute]
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.nio.file.Paths.get(Unknown Source)
	at net.thucydides.core.configuration.MavenOrGradleBuildPath.isAbsolute(MavenOrGradleBuildPath.java:55)
	at net.thucydides.core.configuration.MavenOrGradleBuildPath.getBuildDirectory(MavenOrGradleBuildPath.java:34)
	at net.thucydides.core.configuration.SystemPropertiesConfiguration.loadOutputDirectoryFromSystemProperties(SystemPropertiesConfiguration.java:97)
	at net.thucydides.core.configuration.SystemPropertiesConfiguration.getOutputDirectory(SystemPropertiesConfiguration.java:174)
	at net.serenitybdd.core.SerenityListeners.<init>(SerenityListeners.java:29)
	at cucumber.runtime.formatter.SerenityReporter.initialiseThucydidesListenersFor(SerenityReporter.java:107)
	at cucumber.runtime.formatter.SerenityReporter.handleTestSourceRead(SerenityReporter.java:154)
	at cucumber.runtime.formatter.SerenityReporter.lambda$new$0(SerenityReporter.java:111)
	at cucumber.runner.EventBus.send(EventBus.java:28)
	at cucumber.runtime.model.CucumberFeature.sendTestSourceRead(CucumberFeature.java:132)
	at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:315)
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:80)
	at net.serenitybdd.cucumber.CucumberWithSerenity.<init>(CucumberWithSerenity.java:38)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runner.Computer.getRunner(Computer.java:40)
	at org.junit.runner.Computer$1.runnerForClass(Computer.java:31)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
	at org.junit.runners.Suite.<init>(Suite.java:81)
	at org.junit.runner.Computer.getSuite(Computer.java:28)
	at org.junit.runner.Request.classes(Request.java:75)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
	at io.openbdt.run.SuiteTestRunner.runWithJunit(SuiteTestRunner.java:21)
	at br.com.edglobo.globocore.runner.RunnerTest.test(RunnerTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:254)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

15:40:22  INFO [WebBrowserScreenElement] closing current driver

**Comment by victoroesilva** [comment]
Resolvido.

**Comment by silramos** [comment]
> Resolvido.

Qual foi a solução?
